name: Build and Test

on:
  push:
  pull_request:

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: v24.15.0

      - name: Install frontend dependencies
        run: |
          cd dev-pulse-f
          npm ci

      - name: Build frontend
        run: |
          cd dev-pulse-f
          npm run build

          

